clusterName: onepiece
talosVersion: v1.4.4
kubernetesVersion: v1.27.2
endpoint: https://onepiece.home.local:6443
allowSchedulingOnMasters: true
cniConfig:
  name: none
additionalMachineCertSans:
  - onepiece.home.local
  - 192.168.0.10
additionalApiServerCertSans:
  - 192.168.0.10
nodes:
  - hostname: zoro.home.local
    ipAddress: 192.168.1.200
    installDisk: /dev/sda
    controlPlane: true
    disableSearchDomain: true
    nameservers:
      - 192.168.1.1
      - 1.1.1.1
      - 8.8.8.8
    networkInterfaces:
      - interface: eth0
        mtu: 0
        dhcp: true
        vip:
          ip: 192.168.0.10
    patches:
      - |-
        - op: add
          path: /machine/install/extraKernelArgs
          value:
            - nvme_core.default_ps_max_latency_us=0
  - hostname: sanji.home.local
    ipAddress: 192.168.1.201
    installDisk: /dev/sda
    controlPlane: true
    disableSearchDomain: true
    nameservers:
      - 192.168.1.1
      - 1.1.1.1
      - 8.8.8.8
    networkInterfaces:
      - interface: eth0
        mtu: 0
        dhcp: true
        vip:
          ip: 192.168.0.10
    patches:
      - |-
        - op: add
          path: /machine/install/extraKernelArgs
          value:
            - nvme_core.default_ps_max_latency_us=0
  - hostname: nami.home.local
    ipAddress: 192.168.1.202
    installDisk: /dev/sda
    controlPlane: true
    disableSearchDomain: true
    nameservers:
      - 192.168.1.1
      - 1.1.1.1
      - 8.8.8.8
    networkInterfaces:
      - interface: eth0
        mtu: 0
        dhcp: true
        vip:
          ip: 192.168.0.10
    patches:
      - |-
        - op: add
          path: /machine/install/extraKernelArgs
          value:
            - nvme_core.default_ps_max_latency_us=0
controlPlane:
  patches:
    - |-
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          feature-gates: CronJobTimeZone=true,GracefulNodeShutdown=true
          rotate-server-certificates: "true"
    - |-
      machine:
        time:
          disabled: false
          servers:
            - time.cloudflare.com
worker:
  patches:
    - |-
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          feature-gates: CronJobTimeZone=true,GracefulNodeShutdown=true
          rotate-server-certificates: "true"