---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./sabnzbd/ks.yaml
  - ./plex/ks.yaml
  - ./sonarr/ks.yaml
  - ./radarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./overseerr/ks.yaml
  - ./kaizoku/ks.yaml