---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-uhd-config-v1
  namespace: media
  labels:
    app.kubernetes.io/name: &name sonarr-uhd
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block