---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: sonarr-uhd-restic-secret
  namespace: media
type: Opaque
stringData:
  RESTIC_REPOSITORY: ${SECRET_MINIO_REPOSITORY_S3}/sonarr-uhd
  RESTIC_PASSWORD: ${SECRET_RESTIC_PASSWORD_S3}
  AWS_ACCESS_KEY_ID: ${SECRET_MINIO_ACCESSKEY}
  AWS_SECRET_ACCESS_KEY: ${SECRET_MINIO_SECRETKEY}