---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app kaizoku
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: 'true'
    image:
      repository: ghcr.io/oae/kaizoku
      tag: v1.6.1@sha256:690f805322b11656ca62fb23c7b08439725a9ce9bc59e0e00f6b3c002bd7de44
    env:
      TZ: "Europe/London"
      KAIZOKU_PORT: 3000
      REDIS_HOST: 192.168.2.40
      REDIS_PORT: 6379
      PUID: 1000
      PGID: 1000
      DATABASE_URL: "postgresql://${SECRET_POSTGRES_APPUSER}:${SECRET_POSTGRES_APPUSERPASS}@192.168.2.30:5432/application"
    service:
      main:
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: haproxy
          hajimari.io/icon: mdi:television-classic
        hosts:
          - host: 'kaizoku.home.local'
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        existingClaim: kaizoku-config-v1
      manga:
        enabled: true
        type: nfs
        server: &nas "192.168.1.94"
        path: /mnt/data/manga
        mountPath: /data/manga