---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kaizoku-config-v1
  namespace: media
  labels:
    app.kubernetes.io/name: &name kaizoku
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block