---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
  namespace: kube-system
provisioner: nfs.csi.k8s.io
parameters:
  server: "${NAS}"
  share: "/mnt/data/backup"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]