---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
  annotations:
    meta.helm.sh/release-name: cilium
    meta.helm.sh/release-namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  interval: 15m
  chart:
    spec:
      chart: cilium
      version: 1.14.5
      sourceRef:
        kind: HelmRepository
        name: cilium-charts
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    ipam:
      mode: "kubernetes"
    securityContext:
      privileged: true
    hubble:
      enabled: true
      serviceMonitor:
        enabled: true
      metrics:
        enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
      relay:
        enabled: true
        rollOutPods: true
      ui:
        enabled: true
        rollOutPods: true
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: haproxy
            hajimari.io/enable: "true"
            hajimari.io/appName: hubble
            hajimari.io/icon: lan
          hosts:
            - &host "hubble.${INTERNAL_DOMAIN}"

