---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app sonarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: 'true'
    image:
      repository: ghcr.io/onedr0p/sonarr-develop
      tag: 4.0.0.452@sha256:c6eb356b881e13fe9c8da76e17882624246eeaaf6aee40207d4e66f1c1313378
    env:
      TZ: "Europe/London"
      SONARR__INSTANCE_NAME: Sonarr
      SONARR__APPLICATION_URL: 'http://sonarr.${INTERNAL_DOMAIN}'
      SONARR__LOG_LEVEL: info
    service:
      main:
        ports:
          http:
            port: 8989
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: haproxy
          hajimari.io/icon: mdi:television-classic
        hosts:
          - host: 'sonarr.${INTERNAL_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: 'OnRootMismatch'
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config-v1
      media:
        enabled: true
        type: nfs
        server: &nas "${NAS}"
        path: /mnt
        mountPath: /data
