---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app prowlarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: 'true'
    image:
      repository: ghcr.io/onedr0p/prowlarr-nightly
      tag: 1.5.0.3316@sha256:914d38fee39490801e272d8442eaabf5c45271c0ba0d331058546aa6b9ea7145
    env:
      TZ: "Europe/London"
      PROWLARR__INSTANCE_NAME: Prowlarr
      PROWLARR__LOG_LEVEL: info
    service:
      main:
        ports:
          http:
            port: 9696
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: haproxy
          hajimari.io/icon: mdi:movie-search
        hosts:
          - host: &host 'prowlarr.${INTERNAL_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: 'OnRootMismatch'
    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config-v1