---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kavita
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: kizaing/kavita
      tag: 0.7.8@sha256:48b3c2c07f90feb4641ddb791f96a1bf6e70a2b27da8c8b2ca0cc2c627b91d72
    env:
      TZ: "Europe/London"
    service:
      main:
        ports:
          http:
            port: 5000
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: haproxy
          hajimari.io/icon: "notebook-heart"
        hosts:
          - host: &host "manga.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        existingClaim: kavita-config-v1
        mountPath: /kavita/config
      manga:
        enabled: true
        type: nfs
        server: &nas "${NAS}"
        path: /mnt/data/manga
        mountPath: /data/manga