---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-flaresolver
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: 'true'
spec:
  path: './kubernetes/apps/services/flaresolver/app/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: flaresolver
      namespace: services