---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app radarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: 'true'
    image:
      repository: ghcr.io/onedr0p/radarr-develop
      tag: 5.7.0.8882@sha256:d6a11184848cc5309b9c0024cf33b40bb6a3613a5b15613bcc51864b23839015
    env:
      TZ: "Europe/London"
      RADARR__INSTANCE_NAME: Radarr
      RADARR__APPLICATION_URL: 'http://radarr.${INTERNAL_DOMAIN}'
      RADARR__LOG_LEVEL: info
    service:
      main:
        ports:
          http:
            port: 7878
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: haproxy
          hajimari.io/icon: mdi:television-classic
        hosts:
          - host: 'radarr.${INTERNAL_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: 'OnRootMismatch'
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config-v1
      media:
        enabled: true
        type: nfs
        server: &nas "${NAS}"
        path: /mnt
        mountPath: /data
    resources:
      requests:
        cpu: 50m
        memory: 250Mi
      limits:
        memory: 2000Mi