---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app libreddit
  namespace: services
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
    fullNameOverride: *app
    image:
      repository: ghcr.io/auricom/libreddit
      tag: 0.30.1@sha256:4106b2aa4d9ce76f16ea9db1aa75ace2e9c80c067f698dad2f92c68c7cd94c30
    env:
      LIBREDDIT_DEFAULT_SHOW_NSFW: "on"
      LIBREDDIT_DEFAULT_WIDE: "on"
      LIBREDDIT_DEFAULT_USE_HLS: "on"
      LIBREDDIT_DEFAULT_FRONT_PAGE: "all"
      LIBREDDIT_DEFAULT_HIDE_AWARDS: "on"
      LIBREDDIT_DEFAULT_THEME: "dracula"
    service:
      main:
        ports:
          http:
            port: &port 8080
    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/icon: simple-icons:reddit
          kubernetes.io/ingress.class: haproxy
        hosts:
          - host: 'reddit.${INTERNAL_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /settings
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    resources:
      requests:
        cpu: 5m
        memory: 50Mi
      limits:
        memory: 250Mi