---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: weave-gitops-secret
  namespace: flux-system
type: Opaque
stringData:
  ADMIN_PASSWORDHASH: ${SECRET_WEAVE_PASSWORDHASH}

---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app weave-gitops
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.33
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
  values:
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
    logLevel: info
    adminUser:
      create: true
      username: &admin_user admin
    networkPolicy:
      create: false
    metrics:
      enabled: true
    rbac:
      create: true
      impersonationResourceNames:
        - *admin_user
      additionalRules:
        - apiGroups:
            - 'infra.contrib.fluxcd.io'
          resources:
            - 'terraforms'
          verbs:
            - 'get'
            - 'list'
            - 'patch'
    ingress:
      enabled: true
      annotations:
        probe.home.arpa/enabled: 'false'
        hajimari.io/icon: mdi:sawtooth-wave
        kubernetes.io/ingress.class: haproxy
      hosts:
        - host: &host 'weave.${INTERNAL_DOMAIN}'
          paths:
            - path: /
              pathType: Prefix
  valuesFrom:
    - kind: Secret
      name: weave-gitops-secret
      valuesKey: ADMIN_PASSWORDHASH
      targetPath: adminUser.passwordHash