apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_RESTIC_REPOSITORY_S3: ENC[AES256_GCM,data:NjtvRdYVSVANo5orUwZ7PyBy47otNEIqxFefAHmcFj6NhSg/zgYdc+YcNnSD+/+jYOte,iv:etyVfRejR+R4SvZ3W/KHWXxzdsWj4q7y8sVIkWtdSqE=,tag:Sxa+Zl0KIZqTqo3EBFeiLw==,type:str]
    SECRET_RESTIC_PASSWORD_S3: ENC[AES256_GCM,data:TNpbw5IvV+gCa7mOqMc8g1VAElrjfQr2VB9nkdwwvbwnyPCIymKmhBo=,iv:rOp+T83uk++tHH1EdaY15247XsQjrj93LbGf2390c5o=,tag:7R85siWxbU8xJQ2DcDroBQ==,type:str]
    SECRET_S3_ACCESS_KEY: ENC[AES256_GCM,data:gLYDka2Oi4gym6QuGatlxwAAaR0M1vimHg==,iv:Y8a9SsO4qw8wC8sptPiyBnv4XoCJFYNCwr91NiIxwPI=,tag:ABA9WjofRQkhP9G0gqlkDA==,type:str]
    SECRET_S3_SECRET_KEY: ENC[AES256_GCM,data:JFAnLlFkneE5zJy9QKwNbMQSj957IKuUKYNIJ9ruvQ==,iv:7NfqSq/RkjuapKE4sV+WZqaykePuJXFMnCgvjk2zw6E=,tag:Cvt9FA/jGmL0qZfWMTNTnQ==,type:str]
    SECRET_WEAVE_PASSWORDHASH: ENC[AES256_GCM,data:rFDZYtnDkYM3tRBZA6yVfFActINXr9MdW6FMSPMUOiH/ozyvT+9s5ISNoxLgThWxXbQtvLQPCAlhpWJK,iv:9idvL24kACWa334u4tMj3AQSMqYOcJjtjbCIPyzke/U=,tag:eTTMCa54aCQb/CIgteMBSw==,type:str]
    SECRET_MINIO_ACCESSKEY: ENC[AES256_GCM,data:riFu+ZU=,iv:gVrlcXGz3rRUrwllGkVTzPWF3p3d9UzAl8Wn5eoIBj8=,tag:Q9rsqXTfFzuHXeFZNgjrDA==,type:str]
    SECRET_MINIO_SECRETKEY: ENC[AES256_GCM,data:HniBzYav3og9X+f8BVfINqQdJDtm7ViOl1nKjG7h,iv:tGCj1jQQRcN1lhZG0Ntn3awyhAavbr5HNeJa6nfCfq4=,tag:GXEO2BzS+kjHkF4VrugYgw==,type:str]
    SECRET_MINIO_REPOSITORY_S3: ENC[AES256_GCM,data:148MbhU2lwkcuKfKukdLvvmIICp7unZpcbkG,iv:+q8vLgvXRdq1RS2ZbfziqZZ3dvIrR6NRYt4/RrGkRJc=,tag:D8ITOf9F7RLsjnUB/2BVjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c8gkw6p664dp3x0ycshs5kn3p05phn4vulsh0zhjuzptyfr2vv9s0znrzy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZ3JuSWtQSG8wRmY3ZzZu
            LytsUzVCaEpLeHNGdXRqRnBDcHF1OHczMUdrCkYwY2R4ZUVhR0dYcE5uc1pEanNU
            RlRJT3NDRTIyem5TS2xGc3BJZTJvR1UKLS0tIFdYRjU5T3VQeU9RTmlEU1VReCtu
            aDRRc1Y4c3BIU1pBV1N2U3JpSU1VMk0KbXzhkyXXuFJ2IZduL/qA9ymLqcEOK8Sq
            g+uO5uQeOXEWQrmeqY5QZ13cUf88gS7VtPkc1i7OfI1SGvCXLo5z4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-03T22:32:27Z"
    mac: ENC[AES256_GCM,data:CdL7oXt3rV/ZLwPISpUX/7IWUbrzX6JM1F73KaiZ2Uib5IUWpP1iPY5DyTWQ7vTmh7mzst0CbeZ11xTmiEKSntOYpNMJSR3hc0Ns237Y2cS2hIq48ZmTNAHEjx7WnELNjQH0yidKNui5CL5OTwrOcuwbv47pTIhTlbL92vVw21w=,iv:FzYFo2UcVk+Eyd1jVweODvZ9r6yuDxRuSDkXAYNXS70=,tag:SXWXuUnizqODefO6y4uHDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
