apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_THING: ENC[AES256_GCM,data:vZKzHIIyGZEZ6Q==,iv:+DPmHP2FiXgAk9MTEKdwizodp/NQrP1cDGprQ8dWphA=,tag:m0oaBa8bD6twi+bKPvPQsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c8gkw6p664dp3x0ycshs5kn3p05phn4vulsh0zhjuzptyfr2vv9s0znrzy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabWNrS0p5VFhEc3dSR3VZ
            bCtxNVROb04zKzUyZlp6ajJSYjQ5clVkbUdFCkFNV0ZpZ0trdHBLQTYvUGU2WFlT
            cHR5Zng5MFhjTERHU3VmWk0yam1FcjgKLS0tIEs5WG10NlRMdi9QUXY1Y1NtR1Ju
            Ull5R0dYQm5GNEkzZzFFcEs4L040c00KHn4bb0I2XVJXB6ouCmKaJADrm77HHXky
            +jBkXQXm+qCo/7+8nMMScQioF/O0g/bsrvh6s662R1waHiP6qgw91w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-24T21:29:04Z"
    mac: ENC[AES256_GCM,data:HVlUfJwDJxUQoSoTQqzdr3Pce6S/cBaW5mzlSFTbZxZgb5VnSQFfknpK0WZ5HoCMeNqO97CdRVSZmzm2AUTQxCI3xnyi7DEW/5VL7aTnsuOB92AyefK1OIJJA6fyuuK2Yk69a3jQpjJ/f0bg5V6MG1p3IYHi8u5mXtr8Qz+FHvA=,iv:kQcSRejd3rbiwxJ8JFqrvXQFxCWmbq+seOKszDjrBJM=,tag:0SIZHRyJAJ9HHFnfEQezFw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
