---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  CLUSTER_NAME: onepiece
  LB_RANGE: '192.168.2.1-192.168.2.250'
  LB_HAPROXY: '192.168.2.10'
  LB_PLEX: '192.168.2.20'
