apiVersion: ENC[AES256_GCM,data:yIs=,iv:VqMfrajTNYm8PG79TBPD3mVOWBkwk04ZwA93aAhlxQc=,tag:IqMy0otyviTGG7QxzZez7g==,type:str]
kind: ENC[AES256_GCM,data:j4ij/oW+,iv:PWKEj2IRMP+zOytc57G5E2u0Ns9gd4ADXD7PMMfrhR0=,tag:cZrPhE9u+eRi3F4WhVOhcg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nrvzh2xvd4Mf/e1vOhla,iv:0jeupKb1g1noJ1kM2/2Y07NzHBDBOWxMyzM1zI7yDQY=,tag:YxV8XetZaux312fc1+mioQ==,type:str]
    namespace: ENC[AES256_GCM,data:JLpAac2mpbNmxsw=,iv:zn7lMHG9KE3c0BLpJo+d33rG8Mz13ShHhEuf//k+y+I=,tag:hBOrMow+hJipsJpHBAwIpA==,type:str]
stringData:
    SECRET_THING: ENC[AES256_GCM,data:VSk4I3b4msTMVQ==,iv:aikdkh+dF6vVSU4YsZuKNrtqRNoEZTUF1QZOown4zQQ=,tag:97ftbC4ZRnVfkpJn88oWZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c8gkw6p664dp3x0ycshs5kn3p05phn4vulsh0zhjuzptyfr2vv9s0znrzy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMElqU2k3bklvVTRLOC8r
            UC9CdU5xSGRZdHhsVUp4RTVSaC9Yajg5ZEhvCnlTaXZSZXdwZjVESTRHaHBvM0Uw
            NDJqMVlRWWgzazd3UGNodXJ1ZkJSNU0KLS0tIGgrNGNIZ3psVjNBc1p4ckw5N3JX
            Wno1dWtvUGc3RVRtMmtmOElGV3lhODQK/m7hGOdBnryfd52Nv2zYOaQV2FfpjqxM
            Zjea9NM8Pu5T1PiALeRfp/NviYYsgVwoskfxjTIRgcD+YWT3YDkaZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-17T22:46:57Z"
    mac: ENC[AES256_GCM,data:OjYre9+7ZOL/RZCC72erLoowYEjBSLWieOWi/SWerGEXmNljx12bCIJEvPBR7JKTRwf1yDYtFH9TYd1STJ74R6bT7qEwW3BeRjugTh8mRTvZfQEWP4Anna4vI4NWAN/LB8SX7IuxQbXYBbEI/CYa/Kq6vbYh7qSXZE4rRVxsMeU=,iv:Z3K1qSo+ibDFC9OdjCUyfsnLjgOxPA75Vh5GTyedSqM=,tag:0y5TjZAGOQpKNxzNb65m7Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
