---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # - ./cloudflare-ddns/ks.yaml
  # - ./echoserver/ks.yaml
  # - ./external-dns/ks.yaml
  # - ./ingress-nginx/ks.yaml
  - ./metallb/ks.yaml
  # - ./static-routes/ks.yaml