---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app plex
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/onedr0p/plex-beta
      tag: 1.31.2.6739-a87e876bd@sha256:236fa7e4ebf3209afcc32634129644a29ca7445aa4b6286e296a82b2ac310f76
    env:
      TZ: "Europe/London"
      ADVERTISE_IP: "${LB_PLEX}"
      ALLOWED_NETWORKS: "192.168.0.0/16"
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: "${LB_PLEX}"
        ports:
          http:
            port: &port 32400
    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/icon: mdi:plex
          kubernetes.io/ingress.class: haproxy
        hosts:
          - host: &host "plex.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: plex-config-v1
      anime:
        enabled: true
        type: nfs
        server: &nas "${NAS}"
        path: /mnt/anime-hd-1
        mountPath: /data/anime-hd
      tv:
        enabled: true
        type: nfs
        server: &nas "${NAS}"
        path: /mnt/tv-hd-1
        mountPath: /data/tv-hd
      movies:
        enabled: true
        type: nfs
        server: &nas "${NAS}"
        path: /mnt/movies-hd-1
        mountPath: /data/movies-hd
      transcode:
        enabled: true
        type: emptyDir
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-intel-gpu
                  operator: In
                  values:
                    - "true"
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 100m
        memory: 2000Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 10000Mi
