---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app plex
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/onedr0p/plex-beta
      tag: rolling@sha256:c1e26fcf378ec77e9fa5c486562c3c6497ad0baf7deaff2d9fa33c2a809b69df
    env:
      TZ: "Europe/London"
      ADVERTISE_IP: "${LB_PLEX}"
      ALLOWED_NETWORKS: "192.168.0.0/16"
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: "${LB_PLEX}"
        ports:
          http:
            port: &port 32400
    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/icon: mdi:plex
          kubernetes.io/ingress.class: haproxy
        hosts:
          - host: &host "plex.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: plex-config-v1
      media:
        enabled: true
        type: nfs
        server: &nas "${NAS}"
        path: /mnt
        mountPath: /data
      uhd:
        enabled: true
        type: nfs
        server: *nas
        path: /mnt/tv-uhd-1
        mountPath: /data-uhd
      backup:
        enabled: true
        type: nfs
        server: *nas
        path: /mnt/data/backup/kubernetes/apps/plex
        mountPath: /config/backup
      transcode:
        enabled: true
        type: emptyDir
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-intel-gpu
                  operator: In
                  values:
                    - "true"
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 100m
        memory: 2000Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 10000Mi
