---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: plex-restic-secret
  namespace: media
type: Opaque
stringData:
  RESTIC_REPOSITORY: ${SECRET_RESTIC_REPOSITORY_S3}/plex
  RESTIC_PASSWORD: ${SECRET_RESTIC_PASSWORD_S3}
  AWS_ACCESS_KEY_ID: ${SECRET_S3_ACCESS_KEY}
  AWS_SECRET_ACCESS_KEY: ${SECRET_S3_SECRET_KEY}
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: plex
  namespace: media
spec:
  sourcePVC: plex-config-v1
  trigger:
    schedule: "17 0 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: plex-restic-secret
    cacheCapacity: 2Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    retain:
      daily: 10
      within: 3d
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568